- name: ubuntu basic packages
  hosts: computingInstances
  become: true
  roles:
    - role: basic_packages

- name: ubuntu docker
  hosts: computingInstances
  become: true
  roles:
    - role: docker
