- name: Install net-tools
  apt:
    name: net-tools
    state: present

- name: Install curl
  apt:
    name: curl
    state: present

- name: Install vim
  apt:
    name: vim
    state: present

- name: Install git
  apt:
    name: git
    state: present

- name: Install docker
  include_tasks: install-docker.yaml
