name: CI - Debug

run-name: Debug - ${{ github.ref_name || github.ref}}

on:
  workflow_dispatch: {}

jobs:
  ci_debugger:
    runs-on:
      - master

    steps:
      - name: Template
        run: |
          echo "Hello, world!"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Test - Computing Instance Setup
        env: 
          ANSIBLE_SSH_PW_COMPUTING_INSTANCES: ${{ secrets.ANSIBLE_SSH_PW_COMPUTING_INSTANCES }}
          ANSIBLE_BECOME_PW_COMPUTING_INSTANCES: ${{ secrets.ANSIBLE_BECOME_PW_COMPUTING_INSTANCES }}
        uses: ./.github/actions/computing-instance-setup
